### ISSUE TITLE
Refactor Kustomization Workloads tree view to use flux tree command

### ISSUE THREAD

**Issue by murillodigital** [weaveworks/vscode-gitops-tools#123]
https://fluxcd.io/docs/cmd/flux_tree/

**Comment by kingdonb** [comment]
<img width="326" alt="Screenshot 2023-09-08 at 12 35 53 PM" src="https://github.com/weaveworks/vscode-gitops-tools/assets/3286998/75470150-2575-4364-b5b0-250fa5c804f5">

The tree view has been totally reworked, it now features an expanded as well as compact modes:

![Uploading Screenshot 2023-09-08 at 12.36.18 PM.png…]()
