### ISSUE TITLE
Delete source helm repository 

### ISSUE THREAD

**Issue by usernamehw** [weaveworks/vscode-gitops-tools#145]
A continuation of #115

https://fluxcd.io/docs/cmd/flux_delete_source_helm/

**Comment by kingdonb** [comment]
We will re-test all of the regular functionality for AKS/ARC in v0.26.0, meanwhile please submit feedback after v0.25.1 today which radically overhauled the `kubectl proxy` and client node for informer-based live feedback.

We know there are some issues, #476 but for us it seems like the user experience is about 98% better now, with no manual refresh required. I hope you will like this 🙇
