### ISSUE TITLE
Automatically use compatible algorithm for Azure DevOps Repository

### ISSUE THREAD

**Issue by josefaworks** [weaveworks/vscode-gitops-tools#169]
Flux will use ECDSA as default algorithm for key generation when creating a new `GitRepository`. This algorithm is incompatible with Azure DevOps Git Repositories.

If the repository URL exists within `azure.com` (ie. `git@ssh.dev.azure.com:v3/vscode-development/vscode-development/vscode-development`) add the following option to the `flux` command being executed for `GitRepository` source creation:

`--ssh-key-algorithm rsa`

**Comment by usernamehw** [comment]
Azure cli works without any changes.

`flux` cli doesn't work with the default git implementation `go-git` (maybe https://github.com/fluxcd/source-controller/issues/104):

> ✗ GitRepository reconciliation failed: 'unable to clone 'ssh://git@ssh.dev.azure.com/v3/vscode-development/vscode-development/vscode-development': empty git-upload-pack given'

so, the change enforces 2 arguments `--git-implementation libgit2` and `--ssh-key-algorithm rsa` (Azure cli automatically uses `libgit2` when the git repository is azure devops)

Also, there's now a notification similar to GitHub to open the SSH keys webpage if the source is on `dev.azure.com`.
