### ISSUE TITLE
Add tooltip to Workloads to describe what is included in that definition

### ISSUE THREAD

**Issue by josefaworks** [weaveworks/vscode-gitops-tools#172]
Not all users will immediately understand what workloads means or what they will/won't see in that section of the UI. 

We want to make this as clear as possible to eliminate any confusion.

Microcopy: "Workloads include Helm Releases and Kustomizations, as well as a tree of all other objects created by them"

**Comment by usernamehw** [comment]
![workloads_help_icon](https://user-images.githubusercontent.com/9638156/146007298-fbcad360-5636-4e00-93fe-16721c384019.gif)
