### ISSUE TITLE
Improve documentation for first time users and Azure users.

### ISSUE THREAD

**Issue by murillodigital** [weaveworks/vscode-gitops-tools#176]
Make it clearer for users what to have available in terms of dependencies and how to get started from a clean config.

**Comment by kingdonb** [comment]
We've done some overhaul of the docs, 
<img width="341" alt="Screenshot 2023-09-08 at 12 29 53 PM" src="https://github.com/weaveworks/vscode-gitops-tools/assets/3286998/7b76eb47-77b9-46f6-b244-25e2c87a686e">

The embedded docs as well as the README are regularly updated for each new release ✅
