### ISSUE TITLE
Auto-Install `flux` extension rather than directing to installation page

### ISSUE THREAD

**Issue by jonathan-innis** [weaveworks/vscode-gitops-tools#179]
Rather than being re-directed to the installation page when the flux CLI is not identified on the user machine, the extension should be able to discover the architecture that it is running under and then grab the latest version of `flux` CLI to auto-install without any kind of user action

**Comment by usernamehw** [comment]
On Linux/MacOS the extension runs the official install script: https://fluxcd.io/install.sh

Windows doesn't have an installation file, so it's downloaded, extracted from an archive, moved to AppData folder like `C:\Users\USER_NAME\AppData\Roaming\flux` and added to the User level `Path` environment variable.

On windows the PATH is not refreshed in the VSCode integrated terminal, but the external terminal and commands running by the extension should use the new path.
