### ISSUE TITLE
Enable GitOps script

### ISSUE THREAD

**Issue by csand-msft** [weaveworks/vscode-gitops-tools#184]
Enable GitOps:

currently uses:
az k8s-extension create 
      --name gitops 
      --extension-type microsoft.flux 
      --scope cluster 
      --release-train stable 
      --cluster-name CLUSTER_NAME 
      --cluster-type managedClusters (or connectedClusters for Arc cluster)
      --resource-group RESOURCE_GROUP 
      --subscription SUB_ID

should use: 
az k8s-extension create 
      --extension-type microsoft.flux 
      --scope cluster 
      --cluster-name CLUSTER_NAME 
      --cluster-type managedClusters  (or connectedClusters for Arc cluster)
      --resource-group RESOURCE_GROUP 
      --subscription SUB_ID

This will automatically use the name of "flux" for the extension, which is what automatic install in Azure does.  Also, no need for the --release-train parameter as the extension is in production now.

**Comment by usernamehw** [comment]
Running command without the `--name` parameter:

> ERROR: the following arguments are required: --name/-n

---

So the query will be:

```
az k8s-extension create
--name flux
--extension-type microsoft.flux
--scope cluster
--cluster-name CLUSTER_NAME
--cluster-type managedClusters (or connectedClusters for Arc cluster)
--resource-group RESOURCE_GROUP
--subscription SUB_ID
```

**Comment by csand-msft** [comment]
Verified.  Thanks for the update!
