### ISSUE TITLE
Create Source params are insufficient and incorrect

### ISSUE THREAD

**Issue by csand-msft** [weaveworks/vscode-gitops-tools#186]
When I create a new Source for an Azure AKS cluster I am allowed to enter only these parameters: resource group, cluster name, Azure sub id, which are auto-filled based on the parameters used for the flux extension install.

Then this command is executed:

> az k8s-configuration flux create -n csand-msft-azure-docs-pr-master --scope cluster -u https://github.com/csand-msft/azure-docs-pr.git --branch master --cluster-name Flux2-Preview-AKS-WE --cluster-type managedClusters --resource-group Flux2-Preview-RG-WE --subscription f4f55432-d44f-4de8-82a5-a167aa5382ad

The automatically created config name, repo url, and branch are incorrect.  User needs to be able to specify those as parameters.

User also needs to be able to specify other parameters for the source: 
      Reference type: branch, commit, reference tag, semver range
      Branch: master, main, other
      Sync interval (in minutes)
      Sync timeout (in minutes)
      Source kind: (only "git" supported today, but "bucket" support coming in January)
      Auth Arguments
    --https-ca-cert                : Base64-encoded HTTPS CA certificate for TLS communication with
                                     private repository sync.
    --https-ca-cert-file           : File path to HTTPS CA certificate file for TLS communication
                                     with private repository sync.
    --https-key                    : HTTPS token/password for private repository sync.
    --https-user                   : HTTPS username for private repository sync.
    --known-hosts                  : Base64-encoded known_hosts data containing public SSH keys
                                     required to access private Git instances.
    --known-hosts-file             : File path to known_hosts contents containing public SSH keys
                                     required to access private Git instances.
    --local-auth-ref --local-ref   : Local reference to a kubernetes secret in the configuration
                                     namespace to use for communication to the source.
    --ssh-private-key              : Base64-encoded private ssh key for private repository sync.
    --ssh-private-key-file         : File path to private ssh key for private repository sync.

In addition, the az k8s-configuration flux create command will always create one Kustomization.  If the customer wants control on the parameters for the Kustomization, then this create needs to enable the entry of the Kustomize parameters: ['name',
                                     'path', 'depends_on', 'timeout', 'sync_interval', 'retry_interval', 'prune', 'force'].

**Comment by murillodigital** [comment]
@csand-msft  @usernamehw  `repo url` and `branch` should be identified from the git repo open in VS Code. Are you saying Chris that we should not default to that behavior?  (I guess you had csand-msft/azure-docs-pr open in your VS Studio when you attempted the workload creation, is that correct?) We are also using a naming standard for created kustomizations for various reasons, if I understand your point correctly @csand-msft you are indicating it would be ideal to allow for any name to be chosen by the user?

@usernamehw for any additional parameters choose the most appropriate view, I do think as you indicate, considering the number of available options, a web view is likely best.

**Comment by usernamehw** [comment]
"Create Source" command now opens a webview editor on both generic & Azure clusters:

![Screenshot (384)](https://user-images.githubusercontent.com/9638156/148440514-e9510fde-2aa1-4dda-877d-3b8b7646e178.png)
![Screenshot (386)](https://user-images.githubusercontent.com/9638156/148440524-4de4e023-c128-463e-95dc-40a90f925480.png)

If a git repository is opened in VSCode - then extension prefills `Source Name`, `URL` & `Branch` inputs.

Form doesn't have any validation yet.

**Comment by csand-msft** [comment]
This is good.  One new issue: https://github.com/weaveworks/vscode-gitops-tools/issues/205
