### ISSUE TITLE
Adding source to AKS cluster uses incorrect cluster type

### ISSUE THREAD

**Issue by csand-msft** [weaveworks/vscode-gitops-tools#205]
### Expected behaviour

> az k8s-configuration flux create -n arc-k8s-demo --url "https://github.com/Azure/arc-k8s-demo" --branch "main" --kustomization name="kustomization-a" prune=true --cluster-name Flux2-Preview-AKS-WUS2 **--cluster-type managedClusters** --resource-group Flux2-Preview-RG-WUS2 --subscription f4f55432-d44f-4de8-82a5-a167aa5382ad

The --cluster-type is "managedClusters" for AKS cluster.
The --cluster-type is "connectedClusters" for Arc K8s cluster.

### Actual behaviour

> az k8s-configuration flux create -n arc-k8s-demo --url "https://github.com/Azure/arc-k8s-demo" --branch "main" --kustomization name="kustomization-a" prune=true --cluster-name Flux2-Preview-AKS-WUS2 **--cluster-type connectedClusters** --resource-group Flux2-Preview-RG-WUS2 --subscription f4f55432-d44f-4de8-82a5-a167aa5382ad

### Steps to reproduce

1. Create an AKS cluster in Azure subscription.  
2. Export the kubeconfig context to your local machine (az aks get-credentials --resource-group $resourceGroup --name $aksClusterName).
3. In VS Code GitOps extension, select the cluster context.
4. Enable GitOps (takes a few minutes)
5. Create Source (fill in required params)
6. See that the az k8s-configuration command uses --cluster-type connectedClusters, which is incorrect for an AKS cluster; it should use --cluster-type managedClusters.

### Versions

kubectl version: 1.23
Flux version: 
Git version:
Azure version:
Extension version:  0.17.0
VSCode version:
Operating System (OS) and its version:

Note that I can't find where to execute the GitOps: Show Installed Versions command.

**Comment by usernamehw** [comment]
> Note that I can't find where to execute the GitOps: Show Installed Versions command.

It's in the `Command Palette`. Added  to the issue template e040cca27f3726ae07234fd70b3dd1dd9b275dbd:

![Screenshot (389)](https://user-images.githubusercontent.com/9638156/149652288-958ff73b-db55-46c3-854a-5ef61c57bebe.png)

**Comment by csand-msft** [comment]
Fix verified
