### ISSUE TITLE
Enable or Disable GitOps in Arc-enabled cluster that is also AKS cluster the incorrect --cluster-type is used

### ISSUE THREAD

**Issue by csand-msft** [weaveworks/vscode-gitops-tools#206]
### Expected behaviour

--cluster-type connectedClusters

### Actual behaviour

> az k8s-configuration flux list --cluster-name flux2bb-eus2euap-arc-2 **--cluster-type managedClusters** --resource-group flux2bb-patch --subscription f4f55432-d44f-4de8-82a5-a167aa5382ad
WARNING: Command group 'k8s-configuration flux' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
ERROR: (ResourceNotFound) The Resource 'Microsoft.ContainerService/managedClusters/flux2bb-eus2euap-arc-2' under resource group 'flux2bb-patch' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
Code: ResourceNotFound
Message: The Resource 'Microsoft.ContainerService/managedClusters/flux2bb-eus2euap-arc-2' under resource group 'flux2bb-patch' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix

### Steps to reproduce

1. In Azure create an AKS cluster
2. Set local kubeconfig context to that cluster
3. Arc enable the cluster
4. In VS Code GitOps extension select this cluster context
5. Enable GitOps

This should detect that the cluster is an Arc-enabled cluster and use --cluster-type connectedClusters.

Note that even though the underlying cluster is AKS (resource type managedClusters), by Arc enabling it the key resource type in Azure is connectedClusters.

### Versions

kubectl version:
Flux version:
Git version:
Azure version:
Extension version:
VSCode version:
Operating System (OS) and its version:

**Comment by murillodigital** [comment]
@usernamehw I think what this talks about is cluster type detection priority. ARC takes precedence over alternatives.

**Comment by usernamehw** [comment]
@murillodigital yes, and this commit should change it 0ff7af9fa6024cf48ef544caf72803d4eab6b58a . If someone can test if it works properly now...

**Comment by csand-msft** [comment]
Fix verified
