### ISSUE TITLE
Possibly require specific request to change cluster context

### ISSUE THREAD

**Issue by csand-msft** [weaveworks/vscode-gitops-tools#212]
In the "Clusters" view, in order to change the cluster context, follow the pattern that Kubernetes extension uses where the user right-clicks on a cluster row and a dialog opens with one option "Set as current context".  I think that this explicit approach gives the user clear control.

Currently, in the "Clusters" view of the GitOps extension, when you left-click a cluster row, the current context automatically changes to that cluster.  Not sure if there was a technical reason for implementing this behavior.

**Comment by usernamehw** [comment]
Ok, the wording is different from the Kubernetes extension:

Kubernetes: `Set as Current Cluster`
GitOps: `Set as Current Context`
