### ISSUE TITLE
Azure GitOps supports Bucket source now

### ISSUE THREAD

**Issue by csand-msft** [weaveworks/vscode-gitops-tools#213]
The latest Azure GitOps API supports Bucket source option now.

See https://docs.microsoft.com/azure/azure-arc/kubernetes/tutorial-use-gitops-flux2#bucket-source-arguments for info.

**Comment by usernamehw** [comment]
![Animation](https://user-images.githubusercontent.com/9638156/151975162-33133f2b-c38b-4943-9b80-22a67565f20b.gif)
