### ISSUE TITLE
For new Source in Azure GitOps allow user to set Namespace and Scope

### ISSUE THREAD

**Issue by csand-msft** [weaveworks/vscode-gitops-tools#214]
When creating a new Source for AKS or Arc cluster allow the user to specify the Namespace and the Scope (cluster or namespace).

Currently, defaults to "default" namespace and "cluster" scope.  Devs using this may want a namespace-scoped deployment.

**Comment by usernamehw** [comment]
<img width="500" src="https://user-images.githubusercontent.com/9638156/151706632-85d55b01-015f-4be8-9405-044d764b4dd6.png">
