### ISSUE TITLE
Set AKS cluster as generic

### ISSUE THREAD

**Issue by gbaeke** [weaveworks/vscode-gitops-tools#218]
When using AKS, setting the Cluster Provider to **generic** does not work. Flux is still installed as an extension and some users might not want to use that extra layer in between.

To be precise, I am referring to the installation of Flux itself. I have noticed that after installation via the extension, fluxconfigs are not used anymore (as expected).

**Comment by josefaworks** [comment]
https://github.com/weaveworks/vscode-gitops-tools/issues/217 Duplicate ticket

**Comment by kingdonb** [comment]
We've got a fix for this issue in #248 

Out now as 0.19.2-pre1

Let us know if you're using Flux and the VSCode extension, we'd love to get more feedback 😃

**Comment by kingdonb** [comment]
We have 0.19.2-pre4 today which fixed some other issues.

I'll be pushing out 0.19.2 "final" soon, as I get ready to publish a roadmap for future intended developments 🎉 

Thanks for the great demo video that you recorded, and this feedback!
