### ISSUE TITLE
Question about "Pull Git Repository"

### ISSUE THREAD

**Issue by kingdonb** [weaveworks/vscode-gitops-tools#221]
### Expected behaviour

Should it say "Clone Git Repository" ?

### Actual behaviour

<img width="433" alt="Screen Shot 2022-03-11 at 3 55 17 PM" src="https://user-images.githubusercontent.com/3286998/157963787-c86bf77d-9961-41d1-8678-28e2819093d0.png">

### Steps to reproduce

Right-click a GitRepository under "Sources"

### Versions

kubectl version: v1.23.4
Flux version: v0.27.3
Git version: 2.35.1
Azure version: N/A
Extension version: 0.19.0
VSCode version: 1.64.2 (Universal)
Operating System (OS) and its version: MacOS 12.2.1

**Comment by juozasg** [comment]
A clear name for this action could be: "Clone to Local Folder..."

It could be useful to have this action add the Folder to Workspace - or include a checkbox with default set to "true" ("Add Cloned Folder to Workspace")

**Comment by kingdonb** [comment]
"Clone to ... (Select Directory)" is approximately what I want this widget to say, I think we can relabel this and close it out inside of this next patch release. I think if the user selects a directory outside of the current workspace, then we should finish the clone by automatically opening a new VScode editor session window within that fresh cloned directory.

We should also think about making some workflow for replicating the structure of GitRepository `spec.includes` – if the user has built a hierarchy for us with Flux primitives, we should help them create a full clone in the local filesystem, (I don't know if you can nest includes or why you would want to...) but I think all of that's not needed to close this issue, just thinking!

**Comment by kingdonb** [comment]
"Clone to Local Folder" is fine 👍

**Comment by kingdonb** [comment]
We are maybe going to remove some of these temporarily, the label is not the only problem with this workflow.

I'm marking this for 0.19.6 in case there's any minor enhancement we can add before the demo this afternoon (like, hiding this option altogether if it's not performing correctly)

I'm a bit flustered trying to get everything ready before a presentation, please don't mind the flurry of issue notifications

**Comment by kingdonb** [comment]
The workflow was redone before 0.21.0 🎉 it says "Clone Git Repository..." now and works somewhat better
