### ISSUE TITLE
"Wego" option in menu should say Weave Gitops

### ISSUE THREAD

**Issue by kingdonb** [weaveworks/vscode-gitops-tools#222]
### Expected behaviour

The "wego" brand is deprecated, I think it's either "gitops CLI" or "Weave GitOps" now. Someone please correct me if I'm wrong.

I think it should say "Weave GitOps" here.

### Actual behaviour

<img width="560" alt="Screen Shot 2022-03-11 at 2 40 54 PM" src="https://user-images.githubusercontent.com/3286998/157963345-e86e963a-7121-445f-851b-1320548e7e1e.png">

### Steps to reproduce

In the Documentation widget of the left-hand frame.

### Versions

kubectl version: v1.23.4
Flux version: v0.27.3
Git version: 2.35.1
Azure version: N/A
Extension version: 0.19.0
VSCode version: 1.64.2 (Universal)
Operating System (OS) and its version: MacOS 12.2.1

**Comment by usernamehw** [comment]
It should already be changed: https://github.com/weaveworks/vscode-gitops-tools/pull/220

**Comment by kingdonb** [comment]
Thanks!
