### ISSUE TITLE
Question about this json schema link

### ISSUE THREAD

**Issue by kingdonb** [weaveworks/vscode-gitops-tools#226]
### Expected behaviour

I was unclear about the goal of linking to the JSON schema, or if the link is working as intended:
<img width="700" alt="Screen Shot 2022-03-11 at 4 06 13 PM" src="https://user-images.githubusercontent.com/3286998/157966710-ee87977a-7ea1-4811-b3c2-a214ad486a11.png">

(right above the cursor, click it to go to...)

<img width="576" alt="Screen Shot 2022-03-11 at 4 07 40 PM" src="https://user-images.githubusercontent.com/3286998/157966916-f2a80d1a-29da-4ce7-abf3-ff86a762a98a.png">

Is this our link-widget, and is it meant to retrieve and load the actual JSON Schema in an editor pane?

### Actual behaviour

The JSON schema was loaded in the editor window, it was unclear how directly this behavior benefits the user.

### Steps to reproduce

Connect to a cluster that has a CRD installed and open a file with an instance of that CRD (like HelmRelease) – click the link at the top of the editor frame.

### Versions

kubectl version: v1.23.4
Flux version: v0.27.3
Git version: 2.35.1
Azure version: N/A
Extension version: 0.19.0
VSCode version: 1.64.2 (Universal)
Operating System (OS) and its version: MacOS 12.2.1

**Comment by usernamehw** [comment]
It is a feature of the YAML extension. 
YAML extension creates CodeLens header for all yaml files that have json-schema associated with it.
json-schema provides autocomplete/hover/validation information.

**Comment by kingdonb** [comment]
Alright, then this is nothing to do with our extension. Thanks!
