### ISSUE TITLE
HelmRelease objects in the Workloads view fail to finish loading

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/vscode-gitops-tools#229]
### Expected behaviour

Should expand with the underlying resources

### Actual behaviour

In this case a Kustomization pulled in a HelmRelease object. The Kustomization expands successfully to show the HelmRelease which also expands to show a service and deployment. However, the HelmRelease as a parent object just shows 'loading'

### Steps to reproduce

https://youtu.be/-07emkW8eiM?t=1063

### Versions

kubectl version:
Flux version:
Git version:
Azure version:
Extension version:
VSCode version:
Operating System (OS) and its version:

**Comment by usernamehw** [comment]
Maybe it loaded eventually? 

Flux has a command [`flux tree`](https://fluxcd.io/docs/cmd/flux_tree/) to show tree of objects only for Kustomizations:  so kustomizations tree is loaded very quickly, but HelmRelease tree is fetched by running multiple `kubectl` commands (can take 1+ min).

**Comment by sympatheticmoose** [comment]
That's a fair point - but it still feels theres something off if its taking this long given its only a single deployment and service

**Comment by kingdonb** [comment]
In my example repo where I prepared for the demo we gave and recorded for YouTube, I also tried to reproduce this today

I have two HelmReleases and one of them reproduces the issue, the other does not.

They both seem to be waiting, but Podinfo eventually loads after a few seconds, while ingress-nginx stays at "Loading ..." for at least as long as it takes me to type this out. I haven't seen it move past Loading yet.

<img width="445" alt="Screen Shot 2022-04-30 at 9 49 00 AM" src="https://user-images.githubusercontent.com/3286998/166108220-c299c639-2177-44bc-96c0-4cdc87b573c3.png">

So if this is not just a fluke, you can reproduce it by getting a clone of https://github.com/kingdonb/github-actions-demo

`cd` into `clusters/kind-kind`

and run:
```shell
kustomize build flux-system --reorder=none | kubectl apply -f -
```

This is as I did during the WOUG session we recorded on Thursday. You can do this without my secrets, (the only thing that should not work based on the `secrets` ks that does not become ready is the Slack Notifications. You can disregard that.)

I'm not sure where to attach my debugger to begin inspecting this, but I wanted to document my findings so far.

**Comment by juozasg** [comment]
@usernamehw Im trying to understand this code from a debugger and it looks like sometime the node has 0 children because all of them are filtered out, so it just says 'Loading...'. I need to understand tree views and this code better to debug it

```typescript
async getChildren(workloadNode?: KustomizationNode | HelmReleaseNode) {
  if (workloadNode) {
	  if (workloadNode.children.length) {
		  return workloadNode.children;
	  } else {
		  return [new TreeNode('Loading...')];
	  }
  } else {
	  return await this.buildTree();
  }
}
```

**Comment by usernamehw** [comment]
```ts
async getChildren(workloadNode?: KustomizationNode | HelmReleaseNode) {
	if (workloadNode) {
		// Request for getting children of Kustomization or HelmRelease or one of their child
		if (workloadNode.children.length) {
			// Children is not empty => simply return those tree nodes
			return workloadNode.children;
		} else {
			// Children property is empty (not empty when includes "No Resources" or fetched resources)
			// Assume that the Tree View is still loading
			return [new TreeNode('Loading...')];
		}
	} else {
		// No workload node - root level (build first level objects (Kustomization & HelmRelease nodes))
		return await this.buildTree();
	}
}
```

... What would happen if you assign `children` property at the beginning of `updateWorkloadChildren()` method to that loading message `[new TreeNode('Loading...')]` and remove that if branch from `getChildren()`?

**Comment by usernamehw** [comment]
Or maybe even assign `children` to loading message in the `buildTree()` method?
