### ISSUE TITLE
Update source creation form to allow for Helm Repositories

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/vscode-gitops-tools#231]
When I create a new source from the action on the sources window, the form is restricted to GitRepository objects. I would like to be able to choose between Git/Helm types and have a corresponding form walk me through the process of creating one with appropriate values set.

**Comment by kingdonb** [comment]
<img width="527" alt="Screenshot 2023-09-08 at 12 24 21 PM" src="https://github.com/weaveworks/vscode-gitops-tools/assets/3286998/8ebb7608-de61-4700-b1a9-9a4fe978e7dd">

The latest versions (v0.25.1 is out today) do have a Configure GitOps view that supports all the source kinds, including HelmRepository. 🎖️
