### ISSUE TITLE
Logs formatting and UX improvements

### ISSUE THREAD

**Issue by juozasg** [weaveworks/vscode-gitops-tools#238]
Controlled Logs visual formatting should be improved, and should run and scroll to bottom initially

**Comment by juozasg** [comment]
This is an upstream setting in the `vscode-kubernetes-tools` extension. I've created an issue there: https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1058

**Comment by kingdonb** [comment]
Tracking:

* https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1058

I think we said we were going to try to make this happen upstream, whether that means we need to submit it as a PR and get it merged, or fork the upstream extension if possible so that we can iterate a bit faster than at the pace of two committees...

Moved this to high priority, I think we have other logging enhancements proposed, like

* #254 

and we'd like to get some or all of them into one of the next two upcoming milestones (0.20, 0.21)

**Comment by kingdonb** [comment]
Progress: 

* https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1062

**Comment by SethFalco** [comment]
Just a heads-up, this should hopefully finish more of that issue btw:
https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1066

Hope the implementation was fine for whatever you'll need it for, but feel free to drop a comment on your issue if something is up.

Only part missing is scroll to bottom which I'll do after this is merged.
Meanwhile, seems if word-wrapping is enabled, scroll-to-bottom doesn't work correctly so going to look into that bug. 🤔

**Comment by kingdonb** [comment]
This is great! Thank you @SethFalco I'll look forward to see this land in the kubernetes extension upstream 🎉

**Comment by SethFalco** [comment]
@kingdonb For what it's worth, you can probably make a notification on your extension with a call to action to change those settings for the user?

So maybe on the first time they do a certain action:
> It's recommended to have follow logs and autorun enabled by default. Do you want to apply these settings?
> `Yes` `No` `Don't Ask Again`

Or something like that.

The prompt and applying the settings should be easy enough. The only thing I'm not sure about is what's the right time to notify the user.

**Comment by SethFalco** [comment]
Small update on above!

> The only thing I'm not sure about is what the right time to prompt the user is, and how to make it only once. ^-^'

![image](https://user-images.githubusercontent.com/22801583/168915858-dcaa3963-9c74-450b-bf3c-b981759449eb.png)

Looks like the way Visual Studio Code's built-in extensions handle one-time prompts is by having a `Never Show Again` action button when prompting the user.

Clicking `Never Show Again` sets a setting called `ignore…` i.e. `vscode-gitops-tools.ignoreConfigSuggestions` to `true`.

Pretty simple but it works, I was hoping there'd be a way that didn't create new global settings, but it's not obvious to me anyway. 🤔
