### ISSUE TITLE
Iconography improvements

### ISSUE THREAD

**Issue by juozasg** [weaveworks/vscode-gitops-tools#257]
### Expected behaviour

Left clicking on a resource should still show its status icon in green
![image](https://user-images.githubusercontent.com/4100/165568196-872c232a-aa9e-4d21-9494-e70f9757378a.png)

### Actual behaviour

Status icon greyed out, harder to notice that the resource is Ready
![image](https://user-images.githubusercontent.com/4100/165568384-71acfb9d-8e86-446e-8a92-12d3b71535f4.png)

### Steps to reproduce

Click on a resource in the tree view. 

### Versions

kubectl version:
Flux version:
Git version:
Azure version:
Extension version:
VSCode version:
Operating System (OS) and its version:

**Comment by usernamehw** [comment]
That's how VSCode works. The icon is a standard one (codicon) and its color is ThemeColor. It might work differently if you create icons with hardcoded colors (svg or png) and use them.

**Comment by kingdonb** [comment]
Iconography is improved now in v0.25.1 so you can see Ready, Progressing, Failed. You can also see rollup statuses indicating that something is wrong in the namespace at the top level when all the namespaces are collapsed. The statuses disappear so individual resource statuses can take over when you expand all. There's a weird in-between state when you open up namespaces one by one, but it's not so weird you want to spend any time fixing it... kinda neat.
