### ISSUE TITLE
KUBECONFIG should be user-configured

### ISSUE THREAD

**Issue by kingdonb** [weaveworks/vscode-gitops-tools#266]
Allow setting a different target for $KUBECONFIG

Right now it seems the only (documented?) way to set the kubeconfig source is by setting the KUBECONFIG environment variable. This means it is not possible to switch from one kubeconfig to another while the editor is running, you have to exit, set an environment variable, and then start up the editor again. This should be user-overridable setting that takes precedence over a KUBECONFIG in the environment, through settings.json.

IDK if this issue has been addressed upstream in the vscode-kubernetes extension already, (we should check there first before designing our own answer.)

**Comment by kingdonb** [comment]
It might be useful to allow users to specify multiple files as their kubeconfig

I know that you can do this now, by setting $KUBECONFIG to a colon-delimited list of kubeconfig files, but it is not supported by tools like `kubectx` and I have not tested if it works with our extension either.

It is possible that there is no action taken here, if we already support KUBECONFIG and multiple KUBECONFIG, then building a UI around that seems a bit like tail-chasing, to allow the user to avoid configuring their outside environment.

**Comment by xeijin** [comment]
If this extension is leveraging the `Kubernetes Tools` extension under the hood it would be good if it just respected the values set in `.vscode/settings.json` for that extension, e.g.:

{
    "vs-kubernetes": {
        "vs-kubernetes.kubeconfig": "/Users/xeijin/projects/x8s/provision/kubeconfig",
        "vs-kubernetes.knownKubeconfigs": [
            "/Users/xeijin/projects/x8s/provision/kubeconfig"
        ],
    }
}

**Comment by kingdonb** [comment]
I had a review of how the "set kubeconfig" feature works in Kubernetes extension, it looks nice. I wonder if there's any possibility to share state between this extension and that one? It would be handy if, instead of re-implementing their entire config selection scheme, we could just pluck the config that you have selected with kubernetes vscode extension and use it directly from:

```
const KUBECONFIG_PATH_KEY = "vs-kubernetes.kubeconfig";
```

(the location where the kubeconfig path is stored)

Would it be helpful or more disorienting if we had some state leaking both ways to make the Kubernetes and GitOps extensions behave more cohesively together? I'm thinking that whatever kubeconfig you selected in the Kubernetes extension, you probably want it to be selected in the GitOps extension, and vice-versa. Ideally you can set the kubeconfig from either location, but the experience is seamless when switching between the two extensions.

I do not know how much state sharing or swapping is permitted through the extension sandbox model, I would guess not much. But as I looked to see how much code I would have to copy in order to have a hermetic version that does everything with a kubeconfig the same way that `set kubeconfig` flag does, I think it would really work nicely if they can just share that one bit of state 👍

**Comment by kingdonb** [comment]
There's good news, although it's not in the form of a patch yet, there is a bug instead which prevents you from experiencing the success condition for this user story without knowledge of the workaround. (You have to click the "Refresh Clusters" icon for `set kubeconfig` to take effect.)

We found in our testing that the `set kubeconfig` action in the Kubernetes Tools extension *actually does* set up Flux under the same extension, only it does not update Flux right away, if you change focus enough times it will eventually update on its own, and we noticed that triggering the Clusters tree to refresh "catches up" the Flux extension.

So Flux/GitOps extension actually shares the "set kubeconfig" setting from Kubernetes Tools.

I did some research to find out how we can improve the experience and close the bug. There is a mechanism which we can connect to subscribe the Flux extension to various change events from the Kubernetes extension so that it can remain in sync and provide that seamless experience.

We can subscribe to these events:
* `onDidChangeKubeconfigPath`
* `onDidChangeContext`
* `onDidChangeNamespace` - this one is not useful for the Flux extension right now, but I'm mentioning it for completeness

The events have a subscription available. I just have to do some quick research to understand how to use this to trigger a "refresh clusters" or "refresh workloads/sources" at the right time, and we will have a more seamless and integrated experience with the upstream K8s extension.

The only question I have left is if maybe we shouldn't have a widget that allows the Flux extension to filter by namespace, then it could also react to the `onDidChangeNamespace` event. 🤷

**Comment by kingdonb** [comment]
Here it is, the kubeconfig events PR:

* https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/766

**Comment by alewis001** [comment]
Wow, this is great, thank you @kingdonb. Sorry I've not responded sooner.

I think it's clear in the readme of this extension that it has a dependency on the K8s extension. You could explicitly call out that configuration state is also shared but whether that's entirely necessary or not I don't know. IMHO I'd agree that whatever kubeconfig you've selected you'd want both extensions to be using; I can't think of a situation where I'd want different ones to be active across the two.

Thanks again!

**Comment by alewis001** [comment]
Just gave it a try and it appears to be working perfectly! Thank you!

**Comment by kingdonb** [comment]
Thank you for reporting on the feature, I think we will add it to the docs since managing multiple kubeconfigs is a common pain point and ideally we can add the button to our own view which invokes the existing `set kubeconfig` action without adding another one 👍 then it will be easier to document, or better yet discoverable not requiring documentation.

**Comment by kingdonb** [comment]
I found some show-stopper behaviors when building #333 and #334 that make the current state of this in v0.20.1 and earlier very bad, it does not actually work to use "Set Kubeconfig" if you need any `flux` commands to work, which is most of the point obviously. I believe I have ascertained the root cause and have now created a permanent fix.

The fix will be released in v0.20.2

I have also added:

<img width="869" alt="Screen Shot 2022-07-26 at 1 38 38 PM" src="https://user-images.githubusercontent.com/3286998/181113579-d22d489b-0103-4422-af62-bf1b97bf18b1.png">

access to the "Set Kubeconfig" action in the same UI fashion as kubernetes-tools extension, for convenience, especially for users that never used `kubernetes-tools` extension before at all.

There should be no discontinuity and it should be a seamless experience between the two extensions, as well as for users that just started with GitOps and don't know about kubernetes-tools yet.

Thanks for your patience about this! It's available right now in a prerelease build for testing if you opt-in to the Prerelease channel of the extension.

It should be published on the stable channel tomorrow, and go out to all users, as long as I don't find any more show-stoppers in here while I'm testing on this prerelease. 👍

**Comment by alewis001** [comment]
Thanks! Just after I said it was working, I went back to it and found that I was getting errors as it was trying to connect to localhost for some reason. Unfortunately I didn't have change to report back. However, since applying your latest changes, it appears to be working again 😄

**Comment by kingdonb** [comment]
Yep it would fail any time you were on a non-default kubeconfig, using a `flux` cli command (which should be opaque to the users anyway) but regardless, it should be fixed now! Been testing it myself as well, thanks for the feedback 🎉
