### ISSUE TITLE
Distinguish reconciliation states visually

### ISSUE THREAD

**Issue by dholbach** [weaveworks/vscode-gitops-tools#328]
User feedback

> it would be nice to have an amber state for things that are mid-reconcile and reserve red for when things have actually failed

**Comment by kingdonb** [comment]
Agreed, we can relate this issue with #257 – there are a number of issues with the iconography today, we'll try to close a few of these at once.

**Comment by kingdonb** [comment]
The UX is significantly improved in v0.25.1, [CHANGELOG](https://github.com/weaveworks/vscode-gitops-tools/blob/main/CHANGELOG.md#v0251)

Relevant entries:
* Responsive UI tested with oidc-login
* Kubectl api-resources controls async resource treeview loading
* Namespace UI improvements
* Refactor data providers to not break on context switches

Closes this issue 🎉
