### ISSUE TITLE
GitOps running information message is too generic

### ISSUE THREAD

**Issue by juozasg** [weaveworks/vscode-gitops-tools#383]
Instead of this: 
![image](https://user-images.githubusercontent.com/4100/191726980-3d354afa-c749-4b02-bdc6-e9db2c37df8e.png)

The extension should provide additional info for better user experience:
"Checking Prerequisites"
"Retrieving Metadata"
"Installing Flux"
"Refreshing Clusters"
etc.

**Comment by kingdonb** [comment]
It's certainly doing all of this now, 
<img width="496" alt="Screenshot 2023-09-08 at 12 53 02 PM" src="https://github.com/weaveworks/vscode-gitops-tools/assets/3286998/6f25e3d4-5c0f-4e80-803f-97f1686a944f">

Current release is v0.25.1
