### ISSUE TITLE
Transient states show an error icon

### ISSUE THREAD

**Issue by jeroenlandheer** [weaveworks/vscode-gitops-tools#478]
### Expected behaviour

If something is in an transient state (.e.g. "DependencyNotReady", "Progressing", etc) this should show an icon that indicates an operation is in progress.

This could be something like a play button, a clock, an hourglass, or anything else that shows something is busy.

### Actual behaviour

With transient states we get an icon that is interpreted as an error, a red "X". 

### Steps to reproduce

Reconcile anything with Flux.

### Versions

kubectl version: N/A
Flux version: v2.0
Git version: N/A
Azure version: N/A
Extension version: 0.25.1
VSCode version: 1.81.1
Operating System (OS) and its version: Windows 11 22H2

**Comment by kingdonb** [comment]
Thanks for the feedback! This has already come to our attention separately, but now we have an issue to track it.

Hopefully should be resolved in the next release! We've gotten into an iterative cycle where we are able to release more often now. Are you using the main or prerelease/edge branch, just for information? (The issue currently affects both)

**Comment by kingdonb** [comment]
There is a resolution in the edge branch, which also takes into account when marking the number of good/bad workloads in the count we added to the namespace. We will release it there as soon as we can get CI to pass, and it will go out in a release most likely today.

**Comment by kingdonb** [comment]
Fixed in v0.25.3
