### ISSUE TITLE
Reorganize and refactor all treeviews

### ISSUE THREAD

**Issue by juozasg** [weaveworks/vscode-gitops-tools#497]
Currently we have 4 different treeviews:
* Clusters (Contexts)
* Sources
* Workloads
* WGE
* Documentation

Besides the Clusters view and the static Documentation view, the other 3 views share a lot of common functionality and share a lot of underlying code, but they have various subtle differences and small inconsistencies. The WGE view is especially different, since it groups each type of object at the top level:

<img width="309" alt="image" src="https://github.com/weaveworks/vscode-gitops-tools/assets/4100/cd7478c1-62fc-4e08-a1b5-d22010e47ca7">
<img width="303" alt="image" src="https://github.com/weaveworks/vscode-gitops-tools/assets/4100/153e3a2c-6488-498e-ba29-fe29c24fa2ea">

There should be a single unified view system for all Kubernetes objects and possibly sub-objects (a subset of object metadata). The 3 treeviews either should be replaced with a single view and filter controls, or they should become windows into one shared structure. This should improve performance and reduce bugs and UI inconsistencies.

**Comment by kingdonb** [comment]
All landed in 0.26.0
