### ISSUE TITLE
Add gitops-logo.svg and png icons for extension and gitops view container in activity bar

### ISSUE THREAD

**Issue by RandomFractals** [weaveworks/vscode-gitops-tools#7]
see `icon` field in `package.json` from #4 and view container setup in #3

![weave-gitops-view-container](https://user-images.githubusercontent.com/656833/130093312-05d3faa0-353b-4e21-bd78-419d63b92a02.png)

**Comment by RandomFractals** [comment]
@murillodigital we'll need better icons for this extension and weave gitOps activity bar view container. I used your corp. logo png for now:

![weave-gitops-pic](https://user-images.githubusercontent.com/656833/130098627-2535e6d3-6ecc-4663-9ace-d3bc2dc227a4.png)

**Comment by RandomFractals** [comment]
built-in vscode icons repo with templates to create them: https://github.com/microsoft/vscode-codicons

we need someone to crate custom `gitops-logo.svg` and png icons for light and dark vscode themes using those templates to close this UI ticket.

**Comment by kingdonb** [comment]
<img width="314" alt="Screenshot 2023-09-08 at 12 46 23 PM" src="https://github.com/weaveworks/vscode-gitops-tools/assets/3286998/967f182f-ceeb-48ea-ad9d-63f5de7b3c28">

We have some Flux logos in the extension now, and the extension is on marketplace where the weaveworks branding is in full effect. 🌡️
