### ISSUE TITLE
Describe how replicas and conditions fit in our cluster tree views

### ISSUE THREAD

**Issue by RandomFractals** [weaveworks/vscode-gitops-tools#85]
@murillodigital looking at the output @usernamehw shared for the controllers state update in https://github.com/weaveworks/vscode-gitops-tools/issues/74#issuecomment-924821003, we should start talking about replicas and conditions and how they fit in our clusters tree view.

Maybe we should start adding table views for those objects, configs, and revisions.

_Originally posted by @RandomFractals in https://github.com/weaveworks/vscode-gitops-tools/issues/74#issuecomment-926559737_

**Comment by kingdonb** [comment]
Hello, we have released a new tree view for v0.25.1 that is based on client-node and informer pattern with a controller based design. We found the UX performance is much better and users don't have to click refresh anymore. We know about some minor issues but performance should be overall 98% better, and users can recover from issues with a timeout.

I rate this as better in the worst cases and much better in the average case. I hope you will check it out, please let us know if v0.25.1 works better for you!
